// Code generated by mockery v2.9.4. DO NOT EDIT.

package cmd_mock

import (
	context "context"
	exec "os/exec"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// CommandInterface is an autogenerated mock type for the CommandInterface type
type CommandInterface struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command, arg
func (_m *CommandInterface) Exec(command string, arg ...string) (*exec.Cmd, io.ReadCloser, io.ReadCloser, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(string, ...string) *exec.Cmd); ok {
		r0 = rf(command, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 io.ReadCloser
	if rf, ok := ret.Get(1).(func(string, ...string) io.ReadCloser); ok {
		r1 = rf(command, arg...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	var r2 io.ReadCloser
	if rf, ok := ret.Get(2).(func(string, ...string) io.ReadCloser); ok {
		r2 = rf(command, arg...)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(io.ReadCloser)
		}
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(string, ...string) error); ok {
		r3 = rf(command, arg...)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ExecAndWait provides a mock function with given fields: command, arg
func (_m *CommandInterface) ExecAndWait(command string, arg ...string) (string, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(command, arg...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(command, arg...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecAndWaitCtx provides a mock function with given fields: ctx, command, arg
func (_m *CommandInterface) ExecAndWaitCtx(ctx context.Context, command string, arg ...string) (string, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, command, arg...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, command, arg...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecCtx provides a mock function with given fields: ctx, command, arg
func (_m *CommandInterface) ExecCtx(ctx context.Context, command string, arg ...string) (*exec.Cmd, io.ReadCloser, io.ReadCloser, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) *exec.Cmd); ok {
		r0 = rf(ctx, command, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 io.ReadCloser
	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) io.ReadCloser); ok {
		r1 = rf(ctx, command, arg...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	var r2 io.ReadCloser
	if rf, ok := ret.Get(2).(func(context.Context, string, ...string) io.ReadCloser); ok {
		r2 = rf(ctx, command, arg...)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(io.ReadCloser)
		}
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, string, ...string) error); ok {
		r3 = rf(ctx, command, arg...)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Execute provides a mock function with given fields: env, dir, command, arg
func (_m *CommandInterface) Execute(env map[string]string, dir string, command string, arg ...string) (*exec.Cmd, io.ReadCloser, io.ReadCloser, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, env, dir, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(map[string]string, string, string, ...string) *exec.Cmd); ok {
		r0 = rf(env, dir, command, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 io.ReadCloser
	if rf, ok := ret.Get(1).(func(map[string]string, string, string, ...string) io.ReadCloser); ok {
		r1 = rf(env, dir, command, arg...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	var r2 io.ReadCloser
	if rf, ok := ret.Get(2).(func(map[string]string, string, string, ...string) io.ReadCloser); ok {
		r2 = rf(env, dir, command, arg...)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(io.ReadCloser)
		}
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(map[string]string, string, string, ...string) error); ok {
		r3 = rf(env, dir, command, arg...)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ExecuteAndWait provides a mock function with given fields: env, dir, command, arg
func (_m *CommandInterface) ExecuteAndWait(env map[string]string, dir string, command string, arg ...string) (string, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, env, dir, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(map[string]string, string, string, ...string) string); ok {
		r0 = rf(env, dir, command, arg...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string, string, string, ...string) error); ok {
		r1 = rf(env, dir, command, arg...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteAndWaitCtx provides a mock function with given fields: ctx, env, dir, command, arg
func (_m *CommandInterface) ExecuteAndWaitCtx(ctx context.Context, env map[string]string, dir string, command string, arg ...string) (string, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, env, dir, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string, string, ...string) string); ok {
		r0 = rf(ctx, env, dir, command, arg...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, string, string, ...string) error); ok {
		r1 = rf(ctx, env, dir, command, arg...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteCtx provides a mock function with given fields: ctx, env, dir, command, arg
func (_m *CommandInterface) ExecuteCtx(ctx context.Context, env map[string]string, dir string, command string, arg ...string) (*exec.Cmd, io.ReadCloser, io.ReadCloser, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, env, dir, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string, string, ...string) *exec.Cmd); ok {
		r0 = rf(ctx, env, dir, command, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 io.ReadCloser
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, string, string, ...string) io.ReadCloser); ok {
		r1 = rf(ctx, env, dir, command, arg...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	var r2 io.ReadCloser
	if rf, ok := ret.Get(2).(func(context.Context, map[string]string, string, string, ...string) io.ReadCloser); ok {
		r2 = rf(ctx, env, dir, command, arg...)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(io.ReadCloser)
		}
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, map[string]string, string, string, ...string) error); ok {
		r3 = rf(ctx, env, dir, command, arg...)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}
