// Code generated by mockery 2.9.0. DO NOT EDIT.

package tmpl_mock

import (
	tmpl "github.com/gopaytech/go-commons/pkg/tmpl"
	mock "github.com/stretchr/testify/mock"
)

// TemplateScanOptionFunc is an autogenerated mock type for the TemplateScanOptionFunc type
type TemplateScanOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: scanPath, option
func (_m *TemplateScanOptionFunc) Execute(scanPath string, option tmpl.ScanOption) (tmpl.ScanResult, error) {
	ret := _m.Called(scanPath, option)

	var r0 tmpl.ScanResult
	if rf, ok := ret.Get(0).(func(string, tmpl.ScanOption) tmpl.ScanResult); ok {
		r0 = rf(scanPath, option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tmpl.ScanResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, tmpl.ScanOption) error); ok {
		r1 = rf(scanPath, option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
