// Code generated by mockery 2.9.0. DO NOT EDIT.

package tmpl_mock

import (
	tmpl "github.com/gopaytech/go-commons/pkg/tmpl"
	mock "github.com/stretchr/testify/mock"
)

// TemplateScanFunc is an autogenerated mock type for the TemplateScanFunc type
type TemplateScanFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: scanPath, filter, tmplExt
func (_m *TemplateScanFunc) Execute(scanPath string, filter tmpl.FileFilter, tmplExt string) (tmpl.ScanResult, error) {
	ret := _m.Called(scanPath, filter, tmplExt)

	var r0 tmpl.ScanResult
	if rf, ok := ret.Get(0).(func(string, tmpl.FileFilter, string) tmpl.ScanResult); ok {
		r0 = rf(scanPath, filter, tmplExt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tmpl.ScanResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, tmpl.FileFilter, string) error); ok {
		r1 = rf(scanPath, filter, tmplExt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
