// Code generated by mockery 2.9.0. DO NOT EDIT.

package statsd_mock

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Flush provides a mock function with given fields:
func (_m *Client) Flush() {
	_m.Called()
}

// Increment provides a mock function with given fields: bucket
func (_m *Client) Increment(bucket string) {
	_m.Called(bucket)
}

// Timing provides a mock function with given fields: bucket, value
func (_m *Client) Timing(bucket string, value interface{}) {
	_m.Called(bucket, value)
}
