// Code generated by mockery 2.9.0. DO NOT EDIT.

package statsd_mock

import mock "github.com/stretchr/testify/mock"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// PackageDuration provides a mock function with given fields: duration
func (_m *Publisher) PackageDuration(duration int64) {
	_m.Called(duration)
}
