// Code generated by mockery 2.9.0. DO NOT EDIT.

package seed_mock

import mock "github.com/stretchr/testify/mock"

// Seeder is an autogenerated mock type for the Seeder type
type Seeder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: path
func (_m *Seeder) Execute(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
