// Code generated by mockery 2.9.0. DO NOT EDIT.

package git_mock

import (
	git "github.com/gopaytech/go-commons/pkg/git"
	mock "github.com/stretchr/testify/mock"

	transport "github.com/go-git/go-git/v5/plumbing/transport"
)

// CloneFunc is an autogenerated mock type for the CloneFunc type
type CloneFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: url, destination, auth
func (_m *CloneFunc) Execute(url string, destination string, auth transport.AuthMethod) (git.Repository, error) {
	ret := _m.Called(url, destination, auth)

	var r0 git.Repository
	if rf, ok := ret.Get(0).(func(string, string, transport.AuthMethod) git.Repository); ok {
		r0 = rf(url, destination, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, transport.AuthMethod) error); ok {
		r1 = rf(url, destination, auth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
