// Code generated by mockery v2.28.1. DO NOT EDIT.

package gitlab_mock

import (
	gitlab "github.com/gopaytech/go-commons/pkg/gitlab"
	go_gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// MergeRequest is an autogenerated mock type for the MergeRequest type
type MergeRequest struct {
	mock.Mock
}

// Accept provides a mock function with given fields: projectID, mergeRequestID, removeBranch, whenPipelinePassed
func (_m *MergeRequest) Accept(projectID gitlab.NameOrId, mergeRequestID int, removeBranch bool, whenPipelinePassed bool) (*go_gitlab.MergeRequest, error) {
	ret := _m.Called(projectID, mergeRequestID, removeBranch, whenPipelinePassed)

	var r0 *go_gitlab.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int, bool, bool) (*go_gitlab.MergeRequest, error)); ok {
		return rf(projectID, mergeRequestID, removeBranch, whenPipelinePassed)
	}
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int, bool, bool) *go_gitlab.MergeRequest); ok {
		r0 = rf(projectID, mergeRequestID, removeBranch, whenPipelinePassed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(gitlab.NameOrId, int, bool, bool) error); ok {
		r1 = rf(projectID, mergeRequestID, removeBranch, whenPipelinePassed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Approve provides a mock function with given fields: projectID, mergeRequestID
func (_m *MergeRequest) Approve(projectID gitlab.NameOrId, mergeRequestID int) error {
	ret := _m.Called(projectID, mergeRequestID)

	var r0 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int) error); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: projectID, mergeRequestID
func (_m *MergeRequest) Close(projectID gitlab.NameOrId, mergeRequestID int) error {
	ret := _m.Called(projectID, mergeRequestID)

	var r0 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int) error); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: projectID, sourceBranch, targetBranch, title
func (_m *MergeRequest) Create(projectID gitlab.NameOrId, sourceBranch string, targetBranch string, title string) (*go_gitlab.MergeRequest, error) {
	ret := _m.Called(projectID, sourceBranch, targetBranch, title)

	var r0 *go_gitlab.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string, string) (*go_gitlab.MergeRequest, error)); ok {
		return rf(projectID, sourceBranch, targetBranch, title)
	}
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string, string) *go_gitlab.MergeRequest); ok {
		r0 = rf(projectID, sourceBranch, targetBranch, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(gitlab.NameOrId, string, string, string) error); ok {
		r1 = rf(projectID, sourceBranch, targetBranch, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateToDefault provides a mock function with given fields: projectID, sourceBranch, title
func (_m *MergeRequest) CreateToDefault(projectID gitlab.NameOrId, sourceBranch string, title string) (*go_gitlab.MergeRequest, error) {
	ret := _m.Called(projectID, sourceBranch, title)

	var r0 *go_gitlab.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string) (*go_gitlab.MergeRequest, error)); ok {
		return rf(projectID, sourceBranch, title)
	}
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string) *go_gitlab.MergeRequest); ok {
		r0 = rf(projectID, sourceBranch, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(gitlab.NameOrId, string, string) error); ok {
		r1 = rf(projectID, sourceBranch, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateToMaster provides a mock function with given fields: projectID, sourceBranch, title
func (_m *MergeRequest) CreateToMaster(projectID gitlab.NameOrId, sourceBranch string, title string) (*go_gitlab.MergeRequest, error) {
	ret := _m.Called(projectID, sourceBranch, title)

	var r0 *go_gitlab.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string) (*go_gitlab.MergeRequest, error)); ok {
		return rf(projectID, sourceBranch, title)
	}
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, string, string) *go_gitlab.MergeRequest); ok {
		r0 = rf(projectID, sourceBranch, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(gitlab.NameOrId, string, string) error); ok {
		r1 = rf(projectID, sourceBranch, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: projectID, mergeRequestID
func (_m *MergeRequest) Get(projectID gitlab.NameOrId, mergeRequestID int) (*go_gitlab.MergeRequest, error) {
	ret := _m.Called(projectID, mergeRequestID)

	var r0 *go_gitlab.MergeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int) (*go_gitlab.MergeRequest, error)); ok {
		return rf(projectID, mergeRequestID)
	}
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int) *go_gitlab.MergeRequest); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.MergeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(gitlab.NameOrId, int) error); ok {
		r1 = rf(projectID, mergeRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetApproval provides a mock function with given fields: projectID, mergeRequestID
func (_m *MergeRequest) ResetApproval(projectID gitlab.NameOrId, mergeRequestID int) error {
	ret := _m.Called(projectID, mergeRequestID)

	var r0 error
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId, int) error); ok {
		r0 = rf(projectID, mergeRequestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMergeRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMergeRequest creates a new instance of MergeRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMergeRequest(t mockConstructorTestingTNewMergeRequest) *MergeRequest {
	mock := &MergeRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
