// Code generated by mockery v2.9.4. DO NOT EDIT.

package gitlab_mock

import (
	gitlab "github.com/gopaytech/go-commons/pkg/gitlab"
	go_gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// Project is an autogenerated mock type for the Project type
type Project struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *Project) Get(id gitlab.NameOrId) (*go_gitlab.Project, error) {
	ret := _m.Called(id)

	var r0 *go_gitlab.Project
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId) *go_gitlab.Project); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(gitlab.NameOrId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultBranch provides a mock function with given fields: id
func (_m *Project) GetDefaultBranch(id gitlab.NameOrId) (*go_gitlab.Branch, error) {
	ret := _m.Called(id)

	var r0 *go_gitlab.Branch
	if rf, ok := ret.Get(0).(func(gitlab.NameOrId) *go_gitlab.Branch); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_gitlab.Branch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(gitlab.NameOrId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
