// Code generated by mockery v2.9.4. DO NOT EDIT.

package gitlab_mock

import mock "github.com/stretchr/testify/mock"

// SearchFunc is an autogenerated mock type for the SearchFunc type
type SearchFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: content
func (_m *SearchFunc) Execute(content []byte) bool {
	ret := _m.Called(content)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
