name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup make
      run: sudo apt-get update && sudo apt-get install -y build-essential git curl
      
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Install Task
      uses: arduino/setup-task@v1
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: task test

